# Form implementation generated from reading ui file 'assignment_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AssignmentDialog(object):
    def setupUi(self, AssignmentDialog):
        AssignmentDialog.setObjectName("AssignmentDialog")
        AssignmentDialog.resize(400, 300)
        AssignmentDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssignmentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtWidgets.QLabel(parent=AssignmentDialog)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(parent=AssignmentDialog)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.labelContent = QtWidgets.QLabel(parent=AssignmentDialog)
        self.labelContent.setObjectName("labelContent")
        self.verticalLayout.addWidget(self.labelContent)
        self.textEditContent = QtWidgets.QTextEdit(parent=AssignmentDialog)
        self.textEditContent.setObjectName("textEditContent")
        self.verticalLayout.addWidget(self.textEditContent)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AssignmentDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AssignmentDialog)
        self.buttonBox.accepted.connect(AssignmentDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AssignmentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AssignmentDialog)

    def retranslateUi(self, AssignmentDialog):
        _translate = QtCore.QCoreApplication.translate
        AssignmentDialog.setWindowTitle(_translate("AssignmentDialog", "Добавить/Редактировать задание"))
        self.labelName.setText(_translate("AssignmentDialog", "Название задания:"))
        self.labelContent.setText(_translate("AssignmentDialog", "Содержание задания:"))
