# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 287)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableAssignments = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableAssignments.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableAssignments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableAssignments.setObjectName("tableAssignments")
        self.verticalLayout.addWidget(self.tableAssignments)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddAssignment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddAssignment.setObjectName("btnAddAssignment")
        self.horizontalLayout.addWidget(self.btnAddAssignment)
        self.btnEditAssignment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEditAssignment.setObjectName("btnEditAssignment")
        self.horizontalLayout.addWidget(self.btnEditAssignment)
        self.btnViewVariants = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnViewVariants.setObjectName("btnViewVariants")
        self.horizontalLayout.addWidget(self.btnViewVariants)
        self.btnExportTest = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExportTest.setObjectName("btnExportTest")
        self.horizontalLayout.addWidget(self.btnExportTest)
        self.btnManageStudents = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnManageStudents.setObjectName("btnManageStudents")
        self.horizontalLayout.addWidget(self.btnManageStudents)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление заданиями"))
        self.btnAddAssignment.setText(_translate("MainWindow", "Добавить задание"))
        self.btnEditAssignment.setText(_translate("MainWindow", "Редактировать задание"))
        self.btnViewVariants.setText(_translate("MainWindow", "Просмотр вариантов"))
        self.btnExportTest.setText(_translate("MainWindow", "Экспортировать тест"))
        self.btnManageStudents.setText(_translate("MainWindow", "Редактировать учеников"))
