# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableAssignments = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableAssignments.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableAssignments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableAssignments.setObjectName("tableAssignments")
        self.verticalLayout.addWidget(self.tableAssignments)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 274, 22))
        self.menubar.setObjectName("menubar")
        self.menu_test = QtWidgets.QMenu(parent=self.menubar)
        self.menu_test.setObjectName("menu_test")
        self.menu_assignment = QtWidgets.QMenu(parent=self.menubar)
        self.menu_assignment.setObjectName("menu_assignment")
        MainWindow.setMenuBar(self.menubar)
        self.action_add_assignment = QtGui.QAction(parent=MainWindow)
        self.action_add_assignment.setObjectName("action_add_assignment")
        self.action_add_test = QtGui.QAction(parent=MainWindow)
        self.action_add_test.setObjectName("action_add_test")
        self.action_select_test = QtGui.QAction(parent=MainWindow)
        self.action_select_test.setObjectName("action_select_test")
        self.action_edit_assignment = QtGui.QAction(parent=MainWindow)
        self.action_edit_assignment.setObjectName("action_edit_assignment")
        self.action_export_pdf = QtGui.QAction(parent=MainWindow)
        self.action_export_pdf.setObjectName("action_export_pdf")
        self.action_delete_assignment = QtGui.QAction(parent=MainWindow)
        self.action_delete_assignment.setObjectName("action_delete_assignment")
        self.menu_test.addAction(self.action_select_test)
        self.menu_test.addAction(self.action_export_pdf)
        self.menu_assignment.addAction(self.action_add_assignment)
        self.menu_assignment.addAction(self.action_edit_assignment)
        self.menu_assignment.addAction(self.action_delete_assignment)
        self.menubar.addAction(self.menu_test.menuAction())
        self.menubar.addAction(self.menu_assignment.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление заданиями"))
        self.menu_test.setTitle(_translate("MainWindow", "Тест"))
        self.menu_assignment.setTitle(_translate("MainWindow", "Задание"))
        self.action_add_assignment.setText(_translate("MainWindow", "Добавить задание"))
        self.action_add_test.setText(_translate("MainWindow", "Создать тест"))
        self.action_select_test.setText(_translate("MainWindow", "Выбрать тест"))
        self.action_edit_assignment.setText(_translate("MainWindow", "Редактировать задание"))
        self.action_export_pdf.setText(_translate("MainWindow", "Экспортировать в .pdf"))
        self.action_delete_assignment.setText(_translate("MainWindow", "Удалить задание"))
