# Form implementation generated from reading ui file 'select_test_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectTestDialog(object):
    def setupUi(self, SelectTestDialog):
        SelectTestDialog.setObjectName("SelectTestDialog")
        SelectTestDialog.resize(400, 300)
        SelectTestDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectTestDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SelectTestDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listViewTests = QtWidgets.QListView(parent=SelectTestDialog)
        self.listViewTests.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listViewTests.setObjectName("listViewTests")
        self.verticalLayout.addWidget(self.listViewTests)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SelectTestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelectTestDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectTestDialog)

    def retranslateUi(self, SelectTestDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectTestDialog.setWindowTitle(_translate("SelectTestDialog", "Выбор теста"))
        self.label.setText(_translate("SelectTestDialog", "Выберите тест из списка или создайте новый:"))
